# Generated by Django 6.0 on 2025-12-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="Product",
            new_name="product",
        ),
    ]
